### ISSUE TITLE
'pull access denied for silkyclouds/pmda' through compose

### ISSUE THREAD

**Issue by patach** [silkyclouds/PMDA#2]
Created a custom docker compose based on the docker commands posted on the github.  

Resulted in error:

```
 ✘ pmda Error pull access denied for silkyclouds/pmda, repository does not exist or may require 'docker login': denied: requested access to the resource is denied                                                                                                                   0.4s
Error response from daemon: pull access denied for silkyclouds/pmda, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Compose setup:

```
services:
    pmda:
        container_name: pmda
        ports:
            - 5005:5005
        volumes:
            - ./config/config.json:/app/config.json:ro
            - ./config/ai_prompt.txt:/app/ai_prompt.txt:ro
            - "/home/user/docker-files/plex/plexmediaserver/Library/Application
              Support/Plex Media Server/Plug-in Support/Databases:/database:ro"
            - /home/userdata/Music:/music
            - /home/userdata/temp/music_dupes:/dupes
        image: silkyclouds/pmda:latest
```
